-- AlterTable
ALTER TABLE `aspirasis` MODIFY `status` ENUM('BELUM_DITINDAKLANJUTI', 'SEDANG_DITINDAKLANJUTI', 'SUDAH_DITINDAKLANJUTI', 'TIDAK_BISA_DITINDAKLANJUTI', 'SELESAI') NOT NULL;

-- AlterTable
ALTER TABLE `kegiatans` MODIFY `foto` MEDIUMTEXT NULL;

-- AlterTable
ALTER TABLE `relawans` MODIFY `foto` MEDIUMTEXT NULL;

-- AlterTable
ALTER TABLE `tracking_aspirasis` MODIFY `status` ENUM('BELUM_DITINDAKLANJUTI', 'SEDANG_DITINDAKLANJUTI', 'SUDAH_DITINDAKLANJUTI', 'TIDAK_BISA_DITINDAKLANJUTI', 'SELESAI') NOT NULL;
